### PR TITLE
change dalek dependency to the commit that fixes simd issue

### PR DESCRIPTION
**Pull request by aafshar-poly**

### CODE REVIEW

**Comment by aafshar-poly** [comment]
Meant to submit to a fork.
But, it would be great if you could update your dependency dalek to a version that fixes `packed_simd` issue. You can find more about it in https://github.com/dalek-cryptography/curve25519-dalek/issues/333

**Comment by burdges** [comment]
We cannot publish a git `rev` dependency on crates.io I think, so we must wait until curve25519-dalek fixes this before releasing a version.  Are you just asking for a temporary [`[patch]` fix](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html?highlight=patch#the-patch-section) in master here?

I I understand, this should work either if done here, and maybe if done in your downstream code: 
```
[patch.curve235519-dalek]
packed_simd = { version = "0.3.4", features = ["into_bits"], optional = true }
```
If I `[patch]` here, then you're left using `git = ` for schnorrkel, but if the above works in your downstream code, then we've only one temporary change, right?

**Comment by aafshar-poly** [comment]
Nice, that looks very promising.
For now, I've made o fork https://github.com/PolymathNetwork/schnorrkel and have pinned it to a rev. But I like your solution more, so I'll test it and let you know sometime on Monday.

**Comment by burdges** [comment]
I know crates.io allows `package =` but forbids git dependencies.  I'm unsure about `[patch]` either way, but I'd prefer schnorrkel stay in sync with curve25519-dalek releases if possible.

**Pull request closed without merging**
